-- Hand-written: not generated by drizzle-kit. Registered in the journal so
-- fresh deployments actually get the index; IF NOT EXISTS keeps databases that
-- already have it (applied manually) from failing on re-apply.
CREATE INDEX IF NOT EXISTS "chunks_tsvector_gin_idx" ON "chunks" USING gin ("tsvector");